; PlatformIO Project Configuration
; ESP32-S3 DevKit + Arduino framework

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Увеличиваем стек задачи loop, WebSocket+JSON прожорливы
build_flags =
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson @ ^7.0.4
    ESP32Ping @ ^1.7

; Раскомментируй, если используешь PSRAM
; board_build.arduino.memory_type = qio_opi
; build_flags = -DBOARD_HAS_PSRAM
